// <auto-generated />
namespace ProjectTorpedo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201204042146447_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1XyW7bMBC9F+g/CDq1h5jZDm0gJ0idBUFrJ4ic3Glp7LDlopJUYH9bD/2k/kKH2ixLXpMU6MWQqJk3b4bzOPSfX7+Ds6ng3jNow5Ts+gedfd8DGamYyUnXT+1475N/dvr+XXAZi6n3WNodOTv0lKbrP1mbnBBioicQ1HQEi7Qyamw7kRKExooc7u9/JgcHBBDCRyzPC+5TaZmA7AVfe0pGkNiU8r6KgZtiHb+EGao3oAJMQiPo+ndafYfIDpVOIFad3MH3zjmjSCYEPva95PjkwUBotZKTMKGWUT6cJYDfx5QbKKifJMfbst8/dOwJlVJZhFPyRdn7VV6Y2SVWwM4crSy7rn+Nv3ULtPkKs4UFXML0E9B2dg/jwu8m9j2y6EeajpVbzceFxidpjw59b5ByTkccqgphCUOrNFyDBE0txHfUWtDS+UJGvRW1EcP9llFwK7ChfO+KTSH+BnJin6pIfTotV/DR9x4kw/5DJ6tTqDPL39cH7YOl97hDLtj6BNfj3AMHair+F1iBIROwM84FmEizJG+Zf1qLgMw7qt1nqDBLGW5lwauQj1uGqW20Xe4Sgq11Jkpsjp/rrJN17FISVbi5kkku5VLyZIXmgz5NEqxP7QwoVrwwPwB6e+Hu6hM5BonMEhFWbKtI2Pl0Ao2vGBqZXjFtLPYDHWX90YtFy2y74pbB6jVuqn1e8tLaPeceSw/CTvsUqdfwCtMSKN8sQ6ioLDt8CscwopzqJcdHT/FUyFVH0Drv/GCo+w9ajbQeoa7yOk59fXu0Sut1qGpxe5wFrdexFj608QLS2J1mF5BWGzSO+2ZPrVNk06SKXimzocCgUMPm0dySR27ie1ioZxY7aYQzY0F0nEEn/Ml7nGG+c4M+lWwMBpv6B+CoQfV+aoz2F4xdYkzM/8fZy1zqG6fsjhOnPnblM9XRE9UfBJ1+fP0ozfi+bpDGmKR9o0G6Q3a7Dcf2Mb95Pq4cj7kGMPOR"
                       + "QuI5wWKgvnBytvUYkPqFOsBasckcwl2vJU4KLN0ctLS5kWNVlhozqjMqTZb0BW4jPdeWjWlk8XMExmR98kh5iiaXYgTxjbxNbZLac2NAjPjCfTEg6+Nn14NFzsFttvnmLVJAmsx14q38kjIeV7yv2p24CsL1SKFaZIV3OoSbzCqkgZJbAhXlu4AEpNP8EETCEczcypA+w2pum2u4WLHggtGJpsIUGHN/9/+OuD94p38B1+SDfxIOAAA="; }
        }
    }
}
